# Toolchain for macOS (darwin, arm64)
if(NOT DEFINED CMAKE_C_COMPILER)
  set(CMAKE_C_COMPILER "/usr/bin/clang" CACHE FILEPATH "C compiler")
endif()
if(NOT DEFINED CMAKE_CXX_COMPILER)
  set(CMAKE_CXX_COMPILER "/usr/bin/clang++" CACHE FILEPATH "C++ compiler")
endif()
if(NOT DEFINED CMAKE_SYSTEM_NAME)
  set(CMAKE_SYSTEM_NAME "Darwin" CACHE STRING "System Name")
endif()
if(NOT DEFINED CMAKE_SYSTEM_PROCESSOR)
  set(CMAKE_SYSTEM_PROCESSOR "arm64" CACHE STRING "System Processor")
endif()
set(PLATFORM_ID "darwin-arm64" CACHE STRING "Platform identifier")
set(PLATFORM_DEFINE "PLATFORM_DARWIN_ARM64" CACHE STRING "Preprocessor define for platform")

