# Toolchain for Windows (x86_64, MSVC)
if(NOT DEFINED CMAKE_C_COMPILER)
  set(CMAKE_C_COMPILER "cl.exe" CACHE FILEPATH "C compiler")
endif()
if(NOT DEFINED CMAKE_CXX_COMPILER)
  set(CMAKE_CXX_COMPILER "cl.exe" CACHE FILEPATH "C++ compiler")
endif()
if(NOT DEFINED CMAKE_SYSTEM_NAME)
  set(CMAKE_SYSTEM_NAME "Windows" CACHE STRING "System Name")
endif()
if(NOT DEFINED CMAKE_SYSTEM_PROCESSOR)
  set(CMAKE_SYSTEM_PROCESSOR "x86_64" CACHE STRING "System Processor")
endif()
set(PLATFORM_ID "windows-x86_64-msvc" CACHE STRING "Platform identifier")
set(PLATFORM_DEFINE "PLATFORM_WINDOWS_X86_64_MSVC" CACHE STRING "Preprocessor define for platform")

